name = "asquaredozen_theme"
license = "GNU"
licenselink = "https://github.com/AdamGrossTX/asquaredozen_theme/blob/master/LICENSE"
description = "Hugo Theme for www.asquaredozen.com"
homepage = "https://github.com/AdamGrossTX/asquaredozen_theme/"
tags = ["blog"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "AdamGrossTX"
  homepage = "https://github.com/AdamGrossTX"